### ISSUE TITLE
Is it possible to use this code using arduino?

### ISSUE THREAD

**Issue by happytm** [EBiCS/EBiCS_motor_FOC#1]
Is it possible to use this code using arduino? if not can you provide step by step instructions to upload your code to STM32 please?

Thanks.

**Comment by casainho** [comment]
Hi.
This code is not for Arduino and is complex - it is is meant to be used by developers.

I suggest you to look at SimpleFOC, that firmware is for Arduino!!

**Comment by happytm** [comment]
Thanks.
